
import __ASTRO_IMAGE_IMPORT_1TclI3 from "../../../public/static/rennalabs.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Frennalabs.md";
import __ASTRO_IMAGE_IMPORT_yAulR from "./rick-rubin.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreativity-is-the-final-frontier%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z2cWULD from "./code-is-leverage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcode-is-leverage%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_1uig0z from "../../../public/static/catcafemap.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fcatcafemap.md";
import __ASTRO_IMAGE_IMPORT_230Apr from "./noise-css-cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-add-noise-to-element-css%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1ALxmw from "./adsense-next.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-correct-way-to-load-adsense-in-next-js%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_Z1KR8Yv from "./paths.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthere-is-no-safe-path%2Findex.mdx";
import __ASTRO_IMAGE_IMPORT_ZkR7dv from "../../../public/static/gigfish.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fgigfish.md";
export default new Map([["../../../public/static/rennalabs.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Frennalabs.md", __ASTRO_IMAGE_IMPORT_1TclI3], ["./rick-rubin.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcreativity-is-the-final-frontier%2Findex.mdx", __ASTRO_IMAGE_IMPORT_yAulR], ["./code-is-leverage.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fcode-is-leverage%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z2cWULD], ["../../../public/static/catcafemap.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fcatcafemap.md", __ASTRO_IMAGE_IMPORT_1uig0z], ["./noise-css-cover.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fhow-to-add-noise-to-element-css%2Findex.mdx", __ASTRO_IMAGE_IMPORT_230Apr], ["./adsense-next.webp?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthe-correct-way-to-load-adsense-in-next-js%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1ALxmw], ["./paths.png?astroContentImageFlag=&importer=src%2Fcontent%2Fblog%2Fthere-is-no-safe-path%2Findex.mdx", __ASTRO_IMAGE_IMPORT_Z1KR8Yv], ["../../../public/static/gigfish.png?astroContentImageFlag=&importer=src%2Fcontent%2Fprojects%2Fgigfish.md", __ASTRO_IMAGE_IMPORT_ZkR7dv]]);
		